### ISSUE TITLE
Can't be used anymore

### ISSUE THREAD

**Issue by Luo-hongyi** [snssll/poe2openai#6]
![image](https://github.com/user-attachments/assets/c0774b3a-8cf0-4ff7-bd57-fe832d946901)
```
2024-08-03 15:30:46 INFO:     172.17.0.1:40870 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-08-03 15:30:48 Error in Poe bot: Bot request to GPT-4o-Mini failed on try 0 
2024-08-03 15:30:48  BotError('{"allow_retry": true, "text": "Internal server error (error_id: d3871524-1f1a-49a3-bc8d-315fef0f9a32)"}')
2024-08-03 15:30:50 Error in Poe bot: Bot request to GPT-4o-Mini failed on try 1 
2024-08-03 15:30:50  BotError('{"allow_retry": true, "text": "Internal server error (error_id: da98bc88-6df1-480b-9b3f-b209f06a5b37)"}')
2024-08-03 15:30:50 ERROR:    Exception in ASGI application
2024-08-03 15:30:50 Traceback (most recent call last):
2024-08-03 15:30:50   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 265, in __call__
2024-08-03 15:30:50     await wrap(partial(self.listen_for_disconnect, receive))
2024-08-03 15:30:50   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
2024-08-03 15:30:50     await func()
2024-08-03 15:30:50   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 238, in listen_for_disconnect
2024-08-03 15:30:50     message = await receive()
2024-08-03 15:30:50               ^^^^^^^^^^^^^^^
2024-08-03 15:30:50   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 597, in receive
2024-08-03 15:30:50     await self.message_event.wait()
2024-08-03 15:30:50   File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
2024-08-03 15:30:50     await fut
2024-08-03 15:30:50 asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fab7fc2bf10
2024-08-03 15:30:50 
2024-08-03 15:30:50 During handling of the above exception, another exception occurred:
2024-08-03 15:30:50 
2024-08-03 15:30:50   + Exception Group Traceback (most recent call last):
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
2024-08-03 15:30:50   |     result = await app(  # type: ignore[func-returns-value]
2024-08-03 15:30:50   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2024-08-03 15:30:50   |     return await self.app(scope, receive, send)
2024-08-03 15:30:50   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-08-03 15:30:50   |     await super().__call__(scope, receive, send)
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-08-03 15:30:50   |     await self.middleware_stack(scope, receive, send)
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-08-03 15:30:50   |     raise exc
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-08-03 15:30:50   |     await self.app(scope, receive, _send)
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-08-03 15:30:50   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-08-03 15:30:50   |     raise exc
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-08-03 15:30:50   |     await app(scope, receive, sender)
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-08-03 15:30:50   |     await self.middleware_stack(scope, receive, send)
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-08-03 15:30:50   |     await route.handle(scope, receive, send)
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-08-03 15:30:50   |     await self.app(scope, receive, send)
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-08-03 15:30:50   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-08-03 15:30:50   |     raise exc
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-08-03 15:30:50   |     await app(scope, receive, sender)
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
2024-08-03 15:30:50   |     await response(scope, receive, send)
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 258, in __call__
2024-08-03 15:30:50   |     async with anyio.create_task_group() as task_group:
2024-08-03 15:30:50   |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
2024-08-03 15:30:50   |     raise BaseExceptionGroup(
2024-08-03 15:30:50   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
2024-08-03 15:30:50   +-+---------------- 1 ----------------
2024-08-03 15:30:50     | Traceback (most recent call last):
2024-08-03 15:30:50     |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
2024-08-03 15:30:50     |     await func()
2024-08-03 15:30:50     |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
2024-08-03 15:30:50     |     async for chunk in self.body_iterator:
2024-08-03 15:30:50     |   File "/app/main.py", line 101, in generate
2024-08-03 15:30:50     |     async for chunk in fp.get_bot_response(
2024-08-03 15:30:50     |   File "/usr/local/lib/python3.11/site-packages/fastapi_poe/client.py", line 350, in stream_request
2024-08-03 15:30:50     |     async for message in stream_request_base(
2024-08-03 15:30:50     |   File "/usr/local/lib/python3.11/site-packages/fastapi_poe/client.py", line 483, in stream_request_base
2024-08-03 15:30:50     |     async for message in ctx.perform_query_request(
2024-08-03 15:30:50     |   File "/usr/local/lib/python3.11/site-packages/fastapi_poe/client.py", line 229, in perform_query_request
2024-08-03 15:30:50     |     raise BotError(event.data)
2024-08-03 15:30:50     | fastapi_poe.client.BotError: {"allow_retry": true, "text": "Internal server error (error_id: da98bc88-6df1-480b-9b3f-b209f06a5b37)"}
2024-08-03 15:30:50     +------------------------------------
```

**Comment by snssll** [comment]
In contact with officials and waiting for confirmation of the problem.

**Comment by snssll** [comment]
API begins to respond. Please proceed with testing.
